openapi: 3.0.1
info:
  title: monster-gargoyle
  x-cortex-tag: monster-gargoyle
  x-cortex-custom-metadata:
    alignment: chaotic-neutral
    type: beast
    challenge_rating: 26
    legendary: false
    armor_class: 22
    hit_points: 216
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-gargoyle
      alias: github-token-test
