openapi: 3.0.1
info:
  title: monster-gargoyle
  x-cortex-tag: monster-gargoyle
  x-cortex-custom-metadata:
    alignment: lawful-evil
    type: elemental
    challenge_rating: 2
    legendary: false
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-gargoyle
      alias: github-token-test
